### PR TITLE
Migrate docker_* build targets to use docker cp

### PR DESCRIPTION
**Pull request by simonswine**
- Remove duplicated image <-> docker_image task
- Upgrade golang to 1.10.1 (align with gitlab ci's version)

```release-notes
Fix vault-helper's container build targets (`docker_*`)
```

### CODE REVIEW

**Comment by charlieegan3** [comment]
I tried to run a build

```
# copy artifacts over
if [[ "build" == "build" ]]; then \
        docker cp 5289f9a9974da64c079762424dde062ad820ed4d48b8390c0e15b9b0ecdf8850:/go/src/github.com/jetstack/vault-helper/vault-helper_linux_amd64 vault-helper_linux_amd64; \
fi
/bin/sh: 1: [[: not found
```

**Comment by charlieegan3** [comment]
this works for me:

```diff
        # copy artifacts over
-       if [[ "$*" == "build" ]]; then \
+       if [ "$*" = "build" ]; then \
                docker cp $(CONTAINER_ID):$(CONTAINER_DIR)/vault-helper_linux_amd64 vault-helper_linux_amd64; \
        fi

```

**Comment by simonswine** [comment]
I guess your default shell is not bash or compatible, let me use your variant @charlieegan3

**Comment by charlieegan3** [comment]
I don't know why it didn't work:

```
tarmak|echo $SHELL
/bin/bash
tarmak|/bin/bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright © 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Pull request merged**
